### ISSUE TITLE
Java: add support for precision-increment/0.5 to precision skeleton handling

### ISSUE THREAD

**Issue by hugovdm** [icu-units/icu#104]
The C++ code uses a more sophisticated parseIncrementOption which supports "withMinFraction". Relevant skeletons look like this: "precision-increment/0.5". Test with a unit preference that uses this, and fix the Java implementation.

**Comment by sffc** [comment]
We should check that the precision strings follow a certain format, and fail with an error code if they have an unexpected format. We don't need to support all formats out of the box, until CLDR adds them.

**Comment by sffc** [comment]
People will want currency-per-unit.  So, we will eventually want this.  It seems like a simple fix that we should do now.

**Comment by younies** [comment]
Java code uses precision too https://github.com/unicode-org/icu/blob/5e4fdaf45fa5f6ff0ad9d221b432a65d35762dda/icu4j/main/classes/core/src/com/ibm/icu/impl/units/UnitsRouter.java#L121 

we need to test the behaviour first in order to know if it is working or not.

**Comment by hugovdm** [comment]
Since I couldn't remember what "withMinFraction" was about, I found this in numbertest_api.cpp, which might help clarify - skeleton and fluent API pairs:

            u"precision-increment/0.5"
            NumberFormatter::with().precision(Precision::increment(0.5).withMinFraction(1))

            u"precision-increment/0.50"
            NumberFormatter::with().precision(Precision::increment(0.5).withMinFraction(2))

            u"precision-increment/3.140"
            NumberFormatter::with().precision(Precision::increment(3.14).withMinFraction(3))

Probably not trivial to test this though, because we're not doing dependency injection: tests are using standard resource files and we don't have a way to produce test-specific resource files yet. (In C++, I've also not tested this, I just used the existing `parseIncrementOption`, whereas the Java code has a "parseSkeletonToPrecision" which is very limited.

**Comment by sffc** [comment]
@younies to sync with @hugovdm to identify remaining work.

**Comment by hugovdm** [comment]
My concern was this:

UnitsRouter.java line 121:
https://github.com/unicode-org/icu/blob/3228b200a48375ef1c59e1a0f54eca57d260ee4b/icu4j/main/classes/core/src/com/ibm/icu/impl/units/UnitsRouter.java#L121
This code simply takes off the "precision-increment/" prefix, and returns
`Precision.increment(new BigDecimal(incrementValue));`

The C++ version it was based on, units_router.cpp line 26:
https://github.com/unicode-org/icu/blob/3228b200a48375ef1c59e1a0f54eca57d260ee4b/icu4c/source/i18n/units_router.cpp#L26
calls what used to be `blueprint_helpers::parseIncrementOption()` - to deal with dependencies, I had moved it to number_rounding.cpp - I find it on line 28:
https://github.com/unicode-org/icu/blob/3228b200a48375ef1c59e1a0f54eca57d260ee4b/icu4c/source/i18n/number_rounding.cpp#L28
With https://github.com/unicode-org/icu/commit/81d43a2092b9212059aa8bd0da8ade6654329fbc, I brought back `blueprint_helpers::parseIncrementOption()` to keep it within `blueprint_helpers::`, and made it call `number::impl::parseIncrementOption()` - so the logic lives only in one place, while still having a complete set of blueprint_helpers.

At the time, I reckoned for consistency, the Java version ought to be calling `BlueprintHelpers.parseIncrementOption()`, found here:
https://github.com/unicode-org/icu/blob/3228b200a48375ef1c59e1a0f54eca57d260ee4b/icu4j/main/classes/core/src/com/ibm/icu/number/NumberSkeletonImpl.java#L1385
Or it should be calling a new function factored out of `BlueprintHelpers.parseIncrementOption()`, similar to what the C++ `blueprint_helpers::parseIncrementOption()` now does.

`BlueprintHelpers.parseIncrementOption()` is itself also simpler than C++'s `number::impl::parseIncrementOption()` - always has been - so my concern about the `.withMinFraction(fractionLength)` functionality can be considered out of scope for units work. I also see `BlueprintHelpers.parseIncrementOption()` is marked "private", which might be the Java equivalent of the C++ dependency headaches I had to solve.

If we consider the differences between Java's `BlueprintHelpers.parseIncrementOption()` and C++'s `blueprint_helpers::parseIncrementOption()` out of scope for this issue, I guess my concern can be boiled down to Java having two different implementations of the parseIncrementOption logic:

* BlueprintHelpers.parseIncrementOption(): https://github.com/unicode-org/icu/blob/3228b200a48375ef1c59e1a0f54eca57d260ee4b/icu4j/main/classes/core/src/com/ibm/icu/number/NumberSkeletonImpl.java#L1385
* UnitsRouter.parseSkeletonToPrecision() with an alternative in-line implementation:
 https://github.com/unicode-org/icu/blob/3228b200a48375ef1c59e1a0f54eca57d260ee4b/icu4j/main/classes/core/src/com/ibm/icu/impl/units/UnitsRouter.java#L121
 
If at some point someone wishes to bring the Java version of parseIncrementOption() in line with the C++ implementation, I think it would be good for them to know to also fix the UnitsRouter implementation? Thus perhaps a minimal change that takes care of this concern is having comments in each of the two functions pointing at the alternative implementation. Then the "TODO(icu-units#104)" I added in commit https://github.com/unicode-org/icu/commit/81d43a2092b9212059aa8bd0da8ade6654329fbc , when I was anyway touching the Java code, could be dropped and this issue closed.

**Comment by sffc** [comment]
Thanks for the clarification @hugovdm.  This sounds like a straightforward refactor, then: bring C++ and Java into alignment with regards to how they parse the increment option.

**Comment by younies** [comment]
Move to Jira and implement it.

**Comment by younies** [comment]
moved to Jira https://unicode-org.atlassian.net/browse/ICU-21856
