### ISSUE TITLE
ICU: full Unit Identifier Spec Compliance?

### ISSUE THREAD

**Issue by hugovdm** [icu-units/icu#106]
The spec at https://unicode-org.github.io/cldr/ldml/tr35-general.html#Unit_Identifiers defines:

unit_identifier := long_unit_identifier | mixed_unit_identifier | core_unit_identifier
long_unit_identifier := type "-" core_unit_identifier

We don't currently parse long_unit_identifiers in MeasureUnit::forIdentifier(). If we want to be spec compliant, we need to do so.

**Comment by hugovdm** [comment]
Potential implementations for long_unit_identifier:

1. Check that the first part is a valid type, but initially skip validation. Then parse the rest as a core or mixed identifier. Then, either leave the type unvalidated, or just cross-check that the validated type matches the produced type, when a type is produced.
2. Add all <200 “built-in” units (with type prefixes) to the parsing trie, and if we find one of them, skip the rest of the parsing.

Spec discussion here: https://unicode-org.atlassian.net/browse/CLDR-14253 - I also made the suggestion to not support the "long_unit_identifer" identifier strings.

**Comment by hugovdm** [comment]
I failed to find info on the correct normalized order. Need to check with Mark about this.

**Comment by hugovdm** [comment]
I'll consider unit normalization a part of https://github.com/icu-units/icu/issues/70 - this ticket covering only the question of whether we need to support long_unit_identifiers ?

**Comment by hugovdm** [comment]
Decision from #110 (closed as dupe):
- ignore private-use identifiers: we don't support parsing any units with a unit_component that isn't explicitly known.

For long_unit_identifier validation, determining the expected "type" may depend on extracting the base unit. Extraction of base units is currently in units_converter.cpp, not measunit_extra.cpp. If we do tackle this, the torque examples are noteworthy / may need special-casing (will show up as "energy"). https://unicode-org.atlassian.net/browse/CLDR-14379

**Comment by hugovdm** [comment]
(https://unicode-org.atlassian.net/browse/CLDR-14305 covers similar ground to CLDR-14253 - might be considered a dupe.)

**Comment by sffc** [comment]
Update documentation to specify what type of unit identifier MeasureUnit::forIdentifier is capable of parsing.
