### ISSUE TITLE
Clarify desired precision handling in Java

### ISSUE THREAD

**Issue by hugovdm** [icu-units/icu#107]
Java using BigDecimal means it doesn't have the same constraints as C++.

- Revisiting unit tests to consider what precision behaviour we expect in Java
- ~Given that rounding and carry-back has now implemented in the formatter, I'm wondering whether the "epsilon handling" is even necessary at this point - hence "maybe C++" in the title.~

**Comment by sffc** [comment]
@younies to sync with @hugovdm to figure out if there is an actionable deliverable here. Perhaps review the epsilon handling code and, if necessary, add user documentation for the behavior.

**Comment by hugovdm** [comment]
Some links, I'll give thoughts later:

Epsilon usage in C++:
https://github.com/unicode-org/icu/blob/93b7f6e98de2c323b44bd36b5f7248e23585ac85/icu4c/source/i18n/units_complexconverter.cpp#L167

"Carry-back" (didn't know what to call it) is here:
https://github.com/unicode-org/icu/blob/93b7f6e98de2c323b44bd36b5f7248e23585ac85/icu4c/source/i18n/units_complexconverter.cpp#L247

Java epsilon usage:
https://github.com/unicode-org/icu/blob/93b7f6e98de2c323b44bd36b5f7248e23585ac85/icu4j/main/classes/core/src/com/ibm/icu/impl/units/ComplexUnitsConverter.java#L145

Java "carry-back":
https://github.com/unicode-org/icu/blob/93b7f6e98de2c323b44bd36b5f7248e23585ac85/icu4j/main/classes/core/src/com/ibm/icu/impl/units/ComplexUnitsConverter.java#L249

**Comment by younies** [comment]
Fix the test in C++     `unitsTest->assertEqualsNear(msg.data(), expected, got, 0.0001 * expected);` , we should not multiply by `expected`. After revisiting the `assertEqualNear`

Fix the testing in Java and use `asssertEqualNear`. (visit assertEqualNear)

Revisit point number two.

**Comment by hugovdm** [comment]
I disagree.

JUnit's assertEqualsNear uses an absolute delta, not a relative precision. ICU4C's assertions were modelled on ICU4J's JUnit framework. Thus in https://github.com/unicode-org/icu/commit/65bbf92f782b1be6da7c4deb56512f9f33a2094e I refactored IntlTest::assertEqualsNear() to take an absolute delta.

This also works better for "expected == 0", to avoid divide-by-zero issues in the assert function: better to let the calling code specify absolute detlas, so it can determine how precision of expected-zero should be handled.

**Comment by hugovdm** [comment]
I see in JUnit it's an overloaded method. So my refactoring of assertEqualsNear() was based on wanting to be consistent with this method:
http://junit.sourceforge.net/javadoc/org/junit/Assert.html#assertEquals(java.lang.String,%20double,%20double,%20double)
Please pardon any confusion caused.

My main point was this: simply using `double` is the simplest solution for Java - I'm sure it is faster, it is consistent with the C++ implementatoin, and it supports NaN and Inf. If we're using BigDecimal instead, I'd want it to be due to some useful reason, e.g. having higher precision. And the precision of IEEE 754 `double` is already 15-17 significant decimal digits.

The precision tests I added include "1 light year and 2.1 meters" - which is the mixed unit equivalent of `1.0 + DBL_ESPILON` light years:
https://github.com/unicode-org/icu/blob/93b7f6e98de2c323b44bd36b5f7248e23585ac85/icu4c/source/test/intltest/units_test.cpp#L601

My original two points are thus:

- Do we have a rationale for using BigDecimal in Java? If so: can we document it? Can we make it have higher precision than in C++? If not: we could decide to just leave it as is and not care about it.
- ~The carry-back logic we now have likely means that we don't need the (1 + DBL_EPSILON) logic we originally added (see the "epsilon usage" links in my comment above - https://github.com/icu-units/icu/issues/107#issuecomment-976656783 ). We could experiment with removing that, and seeing if the unit tests still pass.~

Conclusion: this ticket might be "excessive attention to detail" - perhaps we are happy just leaving it as is. However, if we decide we are happy with it as is - then I'd argue we should also consider refactoring Java to use "double" instead of "BigDecimal", if/when we wish to fix the `NaN` and `Inf` handling in Java.

**Comment by hugovdm** [comment]
I experimented with removing some `*(1+epsilon)`, and found it is necessary in ComplexUnitsConverter::convert() because some unit tests test this function directly, without applying a rounder.

It's probably unnecessary in the `applyRounder()` function, because in that case, we'd have rounded to something reasonable for human consumption, and no resonable mixed units should have fractional conversion rates.

units_router.cpp also still has a `*(1+epsilon)` in case there's a unit preference that doesn't have a proper "geq" value: geq is defaulting to 1.0. Conclusion: the `1+eps` code is probably fine.

_I've changed the title of this issue, and struck through the epsilon-related bullets in my previous comment and in the very first comment._

**Comment by younies** [comment]
https://unicode-org.atlassian.net/browse/ICU-21861
