### ISSUE TITLE
Fix conversion precision handling & unit tests in Java (and revisit C++?)

### ISSUE THREAD

**Issue by hugovdm** [icu-units/icu#108]
Java using BigDecimal means it doesn't have the same constraints as C++.

One of the unit tests for the precision behaviour in Java was modified from the C++ version (using a meaningless "1 + 2e-17", unrepresentable by a double, instead of "1 + 2e-16").

Given that rounding and carry-back has now implemented in the formatter, I'm wondering whether the "epsilon handling" is even necessary at this point - hence "maybe C++" in the title.

**Comment by sffc** [comment]
CC @younies

**Comment by hugovdm** [comment]
With my latest PR (1441), I saw the Java code is working very nicely, BigDecimal is doing its thing.

I think it'd be good to experiment with removing the "epsilon tweak" and seeing whether there are still unit tests that break (beyond those that are specifically sensitive to exactly that detail).

**Comment by hugovdm** [comment]
While working on PR 1448, I concluded we should discuss this a bit - to determine desired behaviour of Java / BigDecimal: if we're not using double, it must be because we're aiming for higher precision than double can handle...

Bumping to W2 so we can discuss.

**Comment by hugovdm** [comment]
If we have Java benchmarks, we could demonstrate whether a "double"-based implementation is notably faster. (If so, this may be the easiest solution for feature parity and code similarity with C++, including NaN and Inf support.)

**Comment by hugovdm** [comment]
I see this was a double-filing of #107 (the original text matches the original text of #107).
