### ISSUE TITLE
ICU-21536 Make sure ICU doesn't output zero-valued high-magnitude fields

### ISSUE THREAD

**Issue by sffc** [icu-units/icu#120]
Make sure that ICU doesn't output zero-valued high-order units like "0 feet, 6 inches" based on CLDR preference data.

**Comment by hugovdm** [comment]
Data change needed, something like this:

from:

            <unitPreference regions="AT BE BR CN DE DK DZ EG ES FR HK ID IL IT JO MX MY NL NO PL PT RU SA SE TR VN">meter-and-centimeter</unitPreference>

to:

            <unitPreference regions="AT BE BR CN DE DK DZ EG ES FR HK ID IL IT JO MX MY NL NO PL PT RU SA SE TR VN">meter</unitPreference>
            <unitPreference regions="AT BE BR CN DE DK DZ EG ES FR HK ID IL IT JO MX MY NL NO PL PT RU SA SE TR VN">centimeter</unitPreference>

**Comment by sffc** [comment]
Action items:

- Write unit tests
- Identify data that needs to be updated
- Submit the data changes to CLDR

**Comment by younies** [comment]
move to jira

**Comment by younies** [comment]
https://unicode-org.atlassian.net/browse/ICU-21858
