### ISSUE TITLE
Handle inverse unit usages (link consumption and consumption-inverse)

### ISSUE THREAD

**Issue by hugovdm** [icu-units/icu#124]
In units resources, we have:

- CA, GB and US use consumption-inverse
- other countries use consumption
- both consumption and consumption-inverse have the default fallback, 001, so work entirely independently

Do we want to support converting between the two, or do we treat them as separate entities?

**Comment by hugovdm** [comment]
I've set this to the m1 milestone so that we will discuss this next week.

**Comment by sffc** [comment]
@hugovdm Can you provide some sample unit tests and post them as a reply to this thread with expected and actual output?

**Comment by hugovdm** [comment]
> @hugovdm Can you provide some sample unit tests and post them as a reply to this thread with expected and actual output?

PR 1550 fixes things for C++, though a bit of work remains: Java icudata.jar not updated yet, and inverse handling not generalised to all units. (Small fix needed, coming soon.)
