### ISSUE TITLE
Port more ICU4C tests to ICU4J?

### ISSUE THREAD

**Issue by hugovdm** [icu-units/icu#129]
UnitsDataTest (units_data_test.cpp) has three tests I did not find in ICU4J: testGetUnitCategory, testGetAllConversionRates, testGetPreferencesFor. https://github.com/unicode-org/icu/pull/1550 - currently a draft - could benefit from testGetUnitCategory, but end-to-end testing perhaps also takes care of this. (TBD: how urgently we want to add these tests, or let us choose to deprioritise.

**Comment by younies** [comment]
PR coming today

**Comment by younies** [comment]
`testGetUnitCategory` have added to this PR: https://github.com/unicode-org/icu/pull/1839
