### ISSUE TITLE
Implement Precision handling in UsagePrefsHandler::processQuantity

### ISSUE THREAD

**Issue by hugovdm** [icu-units/icu#13]
Review:
https://github.com/icu-units/icu/pull/5/files/e654dc3edf0a53208a4cdf0798b4c633860dbec3#diff-713f61478dd1772263d4ceebd4b3f7feR97
Starting at number_usageprefs.cpp line 97:

    // TODO(units): here we are always overriding Precision. (1) get precision

**Comment by sffc** [comment]
I think the fallback chain of unit preferences should be:

1. If the programmer specified a precision, use that.
2. Else, if the unit preference data has a precision, use that.
3. Else, use the default precision.

**Comment by hugovdm** [comment]
Depends on https://github.com/icu-units/icu/issues/8

**Comment by hugovdm** [comment]
Work has started, the skeleton parsing code is giving surprising results (possible bug?)

(WIP branch - expect squash/rebase, or request otherwise: https://github.com/hugovdm/icu/tree/output_skeletons)

**Comment by hugovdm** [comment]
Something to dislike about "If the programmer specified a precision, use that": it's basically impossible for the developer to give a locale and preference sensitive rounder. Consider "give miles for long distances, feet otherwise" - the developer doesn't have easy access to which one is selected, and therefore can't give locale and threshold-dependent rounding.

Maybe it's just worth warning the developer: for some usages, overriding behaviour probably does make sense. For those cases, this is worth supporting.
