### ISSUE TITLE
Implement desired behaviour for inverse units other than consumption units

### ISSUE THREAD

**Issue by hugovdm** [icu-units/icu#130]
For consumption units, we specifically support a unit and its inverse, due to mile-per-gallon and liter-per-100-kilometer.

We could generalise this to support all inverse units: if a measurement is specified in hour-per-kilometer, this is technically formattable to speed.

We need to determine appropriate fallback behaviour when a usage is specified and an inverse isn't available.

- Suppose for category "inverse-foo" there is a "usage/default", but only a "usage/default".
- For category "foo", there's a "usage/default" and a "usage/specific" in unitPreferences.
- If someone asks for "usage/specific" with an "inverse-foo" unit, we probably want to format this with the "usage/specific" preference of "foo", rather than fall back to "usage/default" on account of there being an "inverse-foo" unitPreference for this.

This ticket is for tracking the formalising of this decision, and implementing of such inversion with correct fallback logic. (At the time of filing, we're only supporting the inversion of consumption.)

**Comment by hugovdm** [comment]
Assigning to M2 for the sake of discussion, not for implementation. I expect we'll bump this to later miletones, so I've labelled it "future" too.

**Comment by hugovdm** [comment]
*Fallback logic is much simpler now than what the original report mentioned:*
- Old: CLDR Unit Preferences originally had a separate "consumption" and "inverse-consumption", which is where complicated fallback logic concerns came from.
- New: there's just "consumption". We won't have an "inverse-foo" category. Thus fixing the TODO(icu-units#130) in measunit_extra.cpp should become just a small local change in getUnitQuantity() - and unit tests for this.

**Comment by hugovdm** [comment]
Has the decision been formalized?

**Comment by hugovdm** [comment]
@sffc what is the culture regarding Github Issues? Should I personally verify that Issues I opened were appropriately addressed when they are closed, or who is the verifier?

**Comment by sffc** [comment]
We discussed the resolution algorithm in a fair bit of depth in the Morpheus and ICU meetings. Younies implemented a "temporary" algorithm that solves all current known use cases, and filed https://unicode-org.atlassian.net/browse/ICU-21738 for future follow ups.

I don't think we have a formal ticket verification process, but it would be great if you looked at the new ticket and commented with anything else we're still missing! Thanks!
