### ISSUE TITLE
Correct Unit preference & formatting for NaN?

### ISSUE THREAD

**Issue by hugovdm** [icu-units/icu#131]
**In C++,** currently NaN happens to go with the smallest unit preference. Maybe we don't particularly care about this corner case:

    assertFormatSingle(
            u"NaN with Unit Preferences",
            u"measure-unit/area-acre usage/default",
            u"unit/acre usage/default",
            NumberFormatter::with().unit(MeasureUnit::getAcre()).usage("default"),
            Locale::getEnglish(),
            uprv_getNaN(),
            u"NaN cm²");

Infinity (and negative infinity) goes with the largest, as expected:

    assertFormatSingle(
            u"Negative Infinity with Unit Preferences",
            u"measure-unit/area-acre usage/default",
            u"unit/acre usage/default",
            NumberFormatter::with().unit(MeasureUnit::getAcre()).usage("default"),
            Locale::getEnglish(),
            -uprv_getInfinity(),
            u"-∞ km²");

For NaN mixed units like meter-and-centimeter, we get "0 m, NaN cm".

**Comment by sffc** [comment]
2021-05-05: Define, test, and document this behavior.

**Comment by younies** [comment]
Investigate the behaviour in C++ and Java and discuss it next meeting.

**Comment by younies** [comment]
We have tried using this PR: https://github.com/unicode-org/icu/pull/1834 and it does not pay off.

**Comment by hugovdm** [comment]
Clarifying: PR 1834 was considered too late in the release cycle to make it into ICU 70.

I have filed https://unicode-org.atlassian.net/browse/ICU-21864 to track this further, closing this ticket.
