### ISSUE TITLE
Remove minimalPairs

### ISSUE THREAD

**Issue by sffc** [icu-units/icu#133]
It seems that minimalPairs is likely not needed in ICU data.  Consider removing it.

**Comment by hugovdm** [comment]
This is small and relatively quick. Probably doesn't matter whether we do it before or after ICU69.

It's an opportunity to get acquainted with ldml2icu: something Younies might want to do.

**Comment by sffc** [comment]
Mark says it is okay to remove these, but it is low priority.

**Comment by younies** [comment]
@sffc , explain why!

**Comment by sffc** [comment]
1. minimalPairs is a problem not unique to unit formatting.
2. The ICU data build tool already allows removal of this data via config files.
3. This is such a small amount of data that it isn't a good use of our time.
