### ISSUE TITLE
ICU-21123 Homogenize count/gender/case patterns, factor out standard resource-loading-with-lateral-inheritance functions

### ISSUE THREAD

**Issue by hugovdm** [icu-units/icu#138]
From TR #35 section 4.1.2 "Lateral Inheritance" (https://www.unicode.org/reports/tr35/tr35.html#Multiple_Inheritance):

"The following attributes use lateral inheritance for all elements with the DTD root = ldml, except where otherwise noted. The process is applied recursively."

Given how broad-reaching this count/gender/case fallback pattern can be, we should factor out a common function that can be used quite widely. This also means ldml2icu rules intended for use with this need to be homogenized. See TODO markers in ldml2icu files.

**Comment by sffc** [comment]
Lateral fallbacks are typically implemented manually in code. So the way that @hugovdm implemented it is likely correct. Verify that there is no additional work to be done, and then remove the TODOs from the code.

**Comment by sffc** [comment]
Additional note: add additional unit tests for gender (neuter) fallback.

**Comment by younies** [comment]
Finish this by the EOQ

**Comment by younies** [comment]
https://unicode-org.atlassian.net/browse/ICU-21857
