### ISSUE TITLE
ICU-21123 Implement deriveComponent/plural rules, and check CLDR-14499 for */prefix

### ISSUE THREAD

**Issue by hugovdm** [icu-units/icu#139]
As of CLDR 39, the <deriveComponent feature="plural" structure="per" ...> rules all have the same values, as do all the  <deriveComponent feature="plural" structure="prefix" ...> rules. These rules are hard-coded in ICU. I'm thus deprioritising this - unlike the structure="times" and structure="power" rules, where French is different.

When tackling this ticket, also check up on [CLDR-14499](https://unicode-org.atlassian.net/jira/software/c/projects/CLDR/issues/CLDR-14499) which deals with structure="prefix": prefixes have no count or case at the moment, so their deriveComponent rules are also not implemented yet. By contrast, the deriveCompound rules for prefix are considered to have only one parameter (the unit itself, not the prefix).

**Comment by hugovdm** [comment]
More exhaustively noted in code:

    // TODO(icu-units#139):
    // - implement DerivedComponents for "plural/times" and "plural/power":
    //   French has different rules, we'll be producing the wrong results
    //   currently. (Prove via tests!)
    // - implement DerivedComponents for "plural/per", "plural/prefix",
    //   "case/times", "case/power", and "case/prefix" - although they're
    //   currently hardcoded. Languages with different rules are surely on the
    //   way.

**Comment by sffc** [comment]
Start by implementing this logic, and see if there is a good way to test it. If it's easy enough to unit test, then add a unit test, but don't spend too much time reinventing things if it's too difficult to test.

**Comment by younies** [comment]
Move it to Jira and it should be done by ICU 71. (close this)

**Comment by younies** [comment]
https://unicode-org.atlassian.net/browse/ICU-21859
