### ISSUE TITLE
Review handling of built-in units

### ISSUE THREAD

**Issue by hugovdm** [icu-units/icu#145]
* LongNameHandler::forMeasureUnit has code specially for built-ins, while it might be prefereable to have `forArbitraryUnit`'s implementation be "correct" for all cases. (It currently results in failures in unrelated test code.)

* Within forArbitraryUnit and processPatternTimes, we are making use of built-in units when the spec doesn't clearly require this. Revisit the spec and the implementation, and see if we can make these match.

**Comment by younies** [comment]
Move it to Jira and Sync with @hugovdm and close

**Comment by hugovdm** [comment]
Here's the link to the should-be-unnecessary branch in forMeasureUnit:
https://github.com/unicode-org/icu/blob/93b7f6e98de2c323b44bd36b5f7248e23585ac85/icu4c/source/i18n/number_longnames.cpp#L905

If unitRef is not a built-in, we call `forArbitraryUnit` here: https://github.com/unicode-org/icu/blob/93b7f6e98de2c323b44bd36b5f7248e23585ac85/icu4c/source/i18n/number_longnames.cpp#L937

I'd have liked the forArbitraryUnit code path to work for all cases, and wondered why it was causing a test failure.

I've got two TODO(icu-units#145) in number_longnames.cpp, the second is at line 1105 and gives more on the spec:
https://github.com/unicode-org/icu/blob/93b7f6e98de2c323b44bd36b5f7248e23585ac85/icu4c/source/i18n/number_longnames.cpp#L1105

It's probably not necessary to have the code be a direct implementation of the spec, as long as the results are the same. Could again be that my TODOs were about excessive focus on not-important details? :)

**Comment by younies** [comment]
https://unicode-org.atlassian.net/browse/ICU-21860
