### ISSUE TITLE
Work on performance of unit usage and arbitrary unit formatting

### ISSUE THREAD

**Issue by sffc** [icu-units/icu#148]
The performance of unit usage should not be too much slower than formatting of a unit without usage. For example, if `NumberFormatter.withLocale("en").unit("meter").format(100).toString()` takes 10 microseconds, then `NumberFormatter.withLocale("en").unit("meter").usage("road").format(100).toString()` shouldn't take too much longer.  Double or triple total runtime is probably acceptable, but 5x or 10x is probably too slow.

**Comment by sffc** [comment]
Related: #153

**Comment by younies** [comment]
Make sure that the Jira ticket include this request #153 and close.

**Comment by younies** [comment]
https://unicode-org.atlassian.net/browse/ICU-21842
