### ISSUE TITLE
MIXED unit inflection

### ISSUE THREAD

**Issue by hugovdm** [icu-units/icu#150]
* https://unicode-org.atlassian.net/browse/CLDR-14501 requests improved support for list gender, to cover all grammatical genders.
* We also need to know how to handle Unit Display Case for mixed units: shall we start out just assuming case propagates to each individual unit?

**Comment by sffc** [comment]
2021-05-19: Stop-gap solution: use the gender of the first (or last) unit. In future releases, once CLDR has data, do it properly. That work is tracked by the CLDR tickets.

**Comment by younies** [comment]
related CLDR ticket: https://unicode-org.atlassian.net/browse/CLDR-14582

**Comment by younies** [comment]
Investigate what we are doing right now!

**Comment by younies** [comment]
still action on @younies

**Comment by younies** [comment]
https://unicode-org.atlassian.net/browse/ICU-21857
