### ISSUE TITLE
Check unit aliases support in ICU?

### ISSUE THREAD

**Issue by hugovdm** [icu-units/icu#152]
This CLDR PR adds some aliases: https://github.com/unicode-org/cldr/pull/947 - we might want ICU unit tests for them:

* foodcalorie, kilocalorie
* dpcm, pixel-per-centimeter
* dpi, pixel-per-inch
* dot, pixel

dpi and dpcm are not in the validity file (https://github.com/unicode-org/cldr/blob/master/common/validity/unit.xml). They're mentioned at http://cldr.unicode.org/development/development-process/design-proposals/units-pixels-ems-display-resolution .

I'm not sure whether we need to support dpi and dpcm in ICU? (Unit tests could demonstrate how they're being handled.)

**Comment by sffc** [comment]
Note: this is what the aliases look like when they get into the ICU resource bundles:

https://github.com/unicode-org/icu/blob/d4c92ebcfcc62135498052e1629dfa2623807009/icu4c/source/data/unit/root.txt#L340

```
        energy{
            foodcalorie:alias{"/LOCALE/unitsShort/energy/kilocalorie"}
        }
```

**Comment by sffc** [comment]
@younies will add test cases.  If the test passes, great, and close the issue.  If the test fails, more work will be required.
