### ISSUE TITLE
mapping to dbpedia RDF

### ISSUE THREAD

**Issue by srl295** [icu-units/icu#155]
I’m thinking about mapping between RDF objects and CLDR units, similar to what https://unicode-org.atlassian.net/browse/CLDR-7113 proposed for Freebase IDs

The mapping would be something such as:
-  <https://dbpedia.org/resource/Kilometre> == `length-kilometer`

Related item would be mapping to GNU Units, needed for #23

**Comment by srl295** [comment]
related to https://unicode-org.atlassian.net/browse/CLDR-13472

**Comment by sffc** [comment]
@younies will evaluate if there's an easy way to achieve this mapping. If not, we will send it back to CLDR to handle in the next Survey Tool cycle.

**Comment by srl295** [comment]
We have the CLDR-rdf module which does rdf queries inside CLDR if it helps

**Comment by younies** [comment]
sent back to CLDR
