### ISSUE TITLE
Support Mixed Units in NumberFormatter - ICU-20941(a)

### ISSUE THREAD

**Issue by hugovdm** [icu-units/icu#21]
- Route multi-valued output from UnitsRouter
  - Multi-valued "Measure" instances to match the mixed-unit MeasureUnit instance?
- ListFormatter-based formatting

Overlapping ICU ticket: https://unicode-org.atlassian.net/browse/ICU-20941 (also covers arbitrary compound units).

UPDATE 2020-08-18: The scope of this issue is to handle mixed units when `usage` is specified. Follow-up for the general case: #62

**Comment by sffc** [comment]
List format patterns:

    {0}, {1}, and {2}

Output (yard-and-foot-and-inch):

    3 yards, 1 foot, and 11.5 inches

Intermediate (data model = SimpleModifier):

    3 yards, 1 foot, and {0} inches

Call sites to make work:

    NumberFormatter::forSkeleton("unit/yard-and-foot-and-inch").format(3.65)
    // 3 yards, 1 foot, and 11.5 inches

    NumberFormatter::forSkeleton("unit/yard-and-foot-and-inch E0").format(3.51)
    // 3 yards, 1 foot, and 1.15E1 inches

**Comment by hugovdm** [comment]
Conceptually:

    NumberFormatter::forSkeleton("unit/yard-and-foot-and-inch").format(3.65)  // Input is in yards, output is mixed with yards.
    NumberFormatter::forSkeleton("usage/road unit/meter").format(3.65)  // Input is in meters, output locale-dependent.
    NumberFormatter::forSkeleton("usage/road unit/yard-and-foot-and-inch").format(3.65)  // Input is yards, or invalid?

I forgot what example I've been worrying about. Hopefully I'll think of it again soon and express it well, or discover it wasn't anything to worry about.

**Comment by sffc** [comment]
1 and 2 look right.  For 3, both choices are reasonable; pick which one is easier to implement.

**Comment by hugovdm** [comment]
I remembered my question. If we want to support specifying both an input and an output unit, what syntax do we want to use?

.unit() is currently primarily the input unit type, I think it can stay that. We could conceivably add an output unit type as follows:

    NumberFormatter::forSkeleton("unit/kilometer output-unit/mile").format(5);
    NumberFormatter::with().unit(KILOMETER).outputUnit(MILE).format(5);

Inasmuch as I was worrying, I think it was when I hadn't yet recognised "unit" should primarily be _input_, and if we add unit conversions via formatting, we should add a new _output_ parameter, not the other way round. SGTY?

**Comment by hugovdm** [comment]
(We'll have more discussion before I add an output parameter and thus conversion support, I just wanted to have a rough consensus / a sanity check on the path forward, to ensure we don't make things difficult by what we're implementing right now.)

**Comment by sffc** [comment]
The output unit is what gets returned from `FormattedNumber::getOutputUnit()`.  There's no separate setter for it.  A proposal to have a separate setter for the output unit is out of scope of what we're hoping to get done by ICU 68, but you could open a follow-up issue if you feel we should have one.

**Comment by hugovdm** [comment]
Since #62 tracks usage-less mixed units, I'm marking htis one (part one) as done!
