### ISSUE TITLE
Produce ICU data

### ISSUE THREAD

**Issue by sffc** [icu-units/icu#22]
- Normal integration process updates data in ICU from CLDR
- Hugo to sync with David

**Comment by hugovdm** [comment]
Thinking this over again, making sure all bases are covered:

- https://github.com/unicode-org/icu/pull/1173 (merged June 18th) takes care of the Units resources (coming from CLDR XML files). This should be automatic now, no additional documentation necessary.
- https://github.com/icu-units/icu/issues/26 deals with the automatic update of the integration test data files.

Closing!
