### ISSUE TITLE
Load simple unit identifiers

### ISSUE THREAD

**Issue by sffc** [icu-units/icu#25]
Decide whether to load these at runtime from the resource bundles, or add a freshness test.

**Comment by hugovdm** [comment]
Given there's initialization code anyway, and I do indeed still dislike the idea of ICU units support "breaking" with a CLDR data update, requiring code changes, I intend to not go the "freshness test" route: I intend to load the data from the resource file.

Relative to what we have now, we'll have additional conversions from Unicode strings (from units resources) to char* (gSimpleUnits, providing strings that can be referenced when a char* is needed). There are just a bit over 100 strings currently, most of them not longer than 6 characters, and only a dozen are a dozen characters or more (the longest two are 20 characters). :)

This work is also only done when Parser::from is called to parse a measure unit identifier (and only the first time).

**Comment by hugovdm** [comment]
Fixing this as a priority might help give better guidance to https://github.com/icu-units/icu/issues/31 - so I'll tackle this next.
