### ISSUE TITLE
Automate copy of unitsTest.txt and related files from CLDR

### ISSUE THREAD

**Issue by sffc** [icu-units/icu#26]
- CLDR's common/testData/ directory copied into ICU.
- Ticket assigned to Peter: https://unicode-org.atlassian.net/browse/ICU-21066

**Comment by hugovdm** [comment]
First proposal: https://github.com/unicode-org/icu/pull/1199

**Comment by sffc** [comment]
Good progress on this issue.  I think we know what we need to do.  We will address this in September.

**Comment by hugovdm** [comment]
I've updated https://github.com/unicode-org/icu/pull/1199, it now copies to ICU4C and ICU4J.

**Comment by hugovdm** [comment]
https://github.com/unicode-org/icu/pull/1199 has been merged, marking issue as closed!

**Comment by hugovdm** [comment]
Ah, still need to integrate: move from using the old location to the new. Small PR needed, after the next upstream/master merge into units-staging.
