### ISSUE TITLE
ICU-20941 Format arbitrary compound units in NumberFormatter - ICU4C

### ISSUE THREAD

**Issue by sffc** [icu-units/icu#27]
For example: `kibijoule-foot-per-cubic-gigafurlong-square-second`

Links:
- [ICU-21357](https://unicode-org.atlassian.net/browse/ICU-21357) - binary prefixes
- [ICU-20941](https://unicode-org.atlassian.net/browse/ICU-20941) - general "arbitrary compound units" ticket

**Comment by macchiati** [comment]
Note; can point to code in CLDR that does this.

**Comment by hugovdm** [comment]
ICU ticket: https://unicode-org.atlassian.net/browse/ICU-20941

**Comment by sffc** [comment]
Relevant data:

```
            <compoundUnit type="1024p1">
                <unitPrefixPattern>kibi{0}</unitPrefixPattern>
            </compoundUnit>
			<compoundUnit type="10p9">
				<unitPrefixPattern>giga{0}</unitPrefixPattern>
			</compoundUnit>
			<compoundUnit type="power2">
				<compoundUnitPattern1>square {0}</compoundUnitPattern1>
				<compoundUnitPattern1 count="one">square {0}</compoundUnitPattern1>
				<compoundUnitPattern1 count="other">square {0}</compoundUnitPattern1>
			</compoundUnit>
			<compoundUnit type="power3">
				<compoundUnitPattern1>cubic {0}</compoundUnitPattern1>
				<compoundUnitPattern1 count="one">cubic {0}</compoundUnitPattern1>
				<compoundUnitPattern1 count="other">cubic {0}</compoundUnitPattern1>
			</compoundUnit>
            <compoundUnit type="per">
				<compoundUnitPattern>{0} per {1}</compoundUnitPattern>
			</compoundUnit>
            <compoundUnit type="times">
                <compoundUnitPattern>{0}-{1}</compoundUnitPattern>
            </compoundUnit>


			<unit type="energy-joule">
				<displayName>joules</displayName>
				<unitPattern count="one">{0} joule</unitPattern>
				<unitPattern count="other">{0} joules</unitPattern>
			</unit>
			<unit type="length-furlong">
				<displayName>furlongs</displayName>
				<unitPattern count="one">{0} furlong</unitPattern>
				<unitPattern count="other">{0} furlongs</unitPattern>
			</unit>
			<unit type="length-foot">
				<displayName>feet</displayName>
				<unitPattern count="one">{0} foot</unitPattern>
				<unitPattern count="other">{0} feet</unitPattern>
				<perUnitPattern>{0} per foot</perUnitPattern>
			</unit>
			<unit type="speed-meter-per-second">
				<displayName>meters per second</displayName>
				<unitPattern count="one">{0} meter per second</unitPattern>
				<unitPattern count="other">{0} meters per second</unitPattern>
			</unit>
```

**Comment by hugovdm** [comment]
There is work being done for "Derived Grammatical Forms" for CLDR v38. This covers not only how case and gender "propagates" through composed/compound unit, but also plural forms. It means we will only have good information on the correct plural forms after a future CLDR release.

The suggestion is that we handle prefixes and powers for now, but not yet general compound units, since we will not be able to construct them correctly anyway.

An additional concern I just stumbled upon, already affecting just SI prefixes: https://unicode-org.atlassian.net/browse/CLDR-14027 has an example of accents on the prefixes depending on the exact unit prefixed. To make progress on this, we may need to simply do it wrong, for now, for the languages with such complications?

**Comment by hugovdm** [comment]
@macchiati does the CLDR code you refer to have a reasonable approach to plural forms?

**Comment by macchiati** [comment]
Yes. It hasn't been fully wired for the upcoming rules yet ( just for
German rules) but I don't see a problem with extending it.

**Comment by hugovdm** [comment]
Update: PR 1409 improves unit/perUnit handling, but does not tackle any new formatting capability yet - that's coming next!

**Comment by hugovdm** [comment]
Splitting out two new tickets (for a total of three, to have tickets that work better with weekly targets):
- MeasureUnit binary prefixes -> W3, https://github.com/icu-units/icu/issues/114
- Formatting of binary prefixes -> W3, https://github.com/icu-units/icu/issues/115
- Remaining compound units work -> W4, tracking with this ticket.

Supporting binary prefixes will pave much of the way for the rest of this ticket.

**Comment by hugovdm** [comment]
This ticket also needs more data from CLDR, tracked by https://github.com/icu-units/icu/issues/48.
