### ISSUE TITLE
Deal with mixed units that are sorted small-to-big, e.g. "inch-and-foot"

### ISSUE THREAD

**Issue by hugovdm** [icu-units/icu#3]
This Issue tracks "TODO(younies): ensure units being in order by the biggest unit at first."

Rationale:
Currently the description for ComplexUnitConverter::greaterThanOrEqual() asserts the biggest unit is compared. The first unit is compared though, which will break as soon as someone uses a mixed unit ordered small-to-big: "inch+foot".

**Comment by younies** [comment]
For now, we are ensuring that the biggest unit is the first one, thus related to this issue #4 

However, the returning order should not be sorted, I agree, let's track this in this issue.

**Comment by sffc** [comment]
We should have test cases that "inch-and-foot" formats to inches and feet, in that order, and fix things up if necessary.

**Comment by hugovdm** [comment]
In the MicroPropsGenerator for this (LongNamesHandler), the Modifier returned takes one parameter: the smallest, because that's where the fractional values go.

I conclude this MicroPropsGenerator will need to do the sorting. (ComplexUnitConverter will return values sorted from big to small, the MicroPropsGenerator must then sort them back into the specified order.)

**Comment by sffc** [comment]
That's one option.  Is there a reason we can't change ComplexUnitConverter to return the Measures in the correct order?

**Comment by hugovdm** [comment]
Good point - if we save the order in which they are initially requested, prior to sorting them from big to small, that could be quite efficient.

Maybe change the sorting of the list of MeasureUnits to sorting just offsets, allowing an easy inversion of the mapping. I'll look into this when PR 6 is merged?

**Comment by sffc** [comment]
There is not currently locale data that does this.  If it is too hard to implement correctly, consider adding unit tests that make sure that we set an error code or some other reasonable behavior.
