### ISSUE TITLE
MeasureUnit skeletons: produce "unit/" syntax output

### ISSUE THREAD

**Issue by hugovdm** [icu-units/icu#35]
- We should be able to round-trip "unit/kibijoule-per-furlong".
- I think older measure-unit/ and per-measure-unit/ does not support the newest compound units? Determine appropriate behaviour for selecting between those and unit/ ? (Or migrate to unit/ for everything?)

**Comment by sffc** [comment]
The challenge is that we have systems who rely on the skeleton output to rell what options were set.  For example, people search the skeleton string for "measure-unit/length-meter" to tell whether or not meters are being used.  If we start spitting out "unit/meter", we would break those clients.

A potential solution might be to print "measure-unit" for built-in units (those with a type and subtype), and "unit" for non-built-in units (those with only an identifier string).

**Comment by hugovdm** [comment]
Somewhat surprising:
- normalizing `"measure-unit/speed-meter-per-second"` is no change (it round-trips)
- normalizing `NumberFormatter::with().unit(MeasureUnit::getMeterPerSecond())` results in `"measure-unit/speed-meter-per-second"`

But:
- normalizing `"unit/meter-per-second"` results in `"measure-unit/length-meter per-measure-unit/duration-second"` for some reason?

This ticket should take care of reasonable behaviour for such cases.

**Comment by hugovdm** [comment]
Turns out this may be required for https://github.com/icu-units/icu/issues/62 - since `assertFormatSingle` highlights that mixed units result in invalid skeletons.

**Comment by sffc** [comment]
Sounds like assertFormatSingle is doing its job 🙂

**Comment by hugovdm** [comment]
First draft of a document on skeleton behaviour and proposals for the future, anyone with the link can currently view and commenting: https://docs.google.com/document/d/1nidDTiLVzwvI4FNdLul0qtW0mA1F34BxyytgI64YkNM/edit

**Comment by hugovdm** [comment]
Kibi- prefixes not supported by MeasureUnit yet. I'm considering kibi- out of scope for this ticket, but leaving in the commented-out test.

**Comment by hugovdm** [comment]
Should be fixed as soon as 1347 is merged.
