### ISSUE TITLE
Decide on error handling for usage, relative to unit identifier handling

### ISSUE THREAD

**Issue by hugovdm** [icu-units/icu#36]
Since unit identifiers are parsed properly from number skeletons, an invalid identifier results in U_NUMBER_SKELETON_SYNTAX_ERROR.

For `usage/` strings, we currently accept any string, and only notice failure when we try to fetch the usage from resources. We consequently fail with U_MISSING_RESOURCE_ERROR for invalid usages.

Should we try to return U_NUMBER_SKELETON_SYNTAX_ERROR instead, when an invalid usage is specified as skeleton? (Also check consistency of errors when constructing without skeletons?)

- Currently: Unit Identifier parsing is hard-coded (to be reconsidered in https://github.com/icu-units/icu/issues/25), Usage handling is entirely runtime, resource-based.

**Comment by sffc** [comment]
One challenge is that we don't actually know about the invalid usage until we construct the object.  That's too late to know about it in the skeleton parser.  Maybe this is okay and we don't need to do early detection of the invalid usage.

However, I think `U_MISSING_RESOURCE_ERROR` is the wrong error, regardless of whether a skeleton is in use.  `U_INVALID_ARGUMENT_ERROR` would be marginally better, but maybe `U_INVALID_FORMAT_ERROR` or something similar would be the right one.  Search *utypes.h* for one that sounds appropriate to you. :)

**Comment by hugovdm** [comment]
For unit identifier parsing, I believe we'll end up loading just over 100 strings from the units resources file.

Compare to usage strings: there are currently 15 categories, 39 usages across those 15 categories, only 21 unique strings. We could very much consider loading these for checking usage values - but it would still be just a partial value checking if we're not checking category&usage together.

Benefit of doing so is probably negligible anyway. I'm rather thinking again about unitConstants loading at runtime. :)
