### ISSUE TITLE
Sort the Mixed units from the biggest to the smallest in the `ComplexUnitConverter`

### ISSUE THREAD

**Issue by younies** [icu-units/icu#4]

**Comment by younies** [comment]
@sffc , @hugovdm 
Quick question, if a unit is greater than another unit (e.g `foot` > `inch`)

Thus means the index of the bigger unit is bigger than  the smaller one ?

**Comment by sffc** [comment]
> @sffc , @hugovdm , @hagbard
> Quick question, if a unit is greater than another unit (e.g `foot` > `inch`)
> 
> Thus means the index of the bigger unit is bigger than the smaller one ?

Yes, the simple unit Identifiers are sorted by size, except you need to handle differences in dimensionality and SI prefix.

**Comment by sffc** [comment]
The PR is merged
