### ISSUE TITLE
Support complex units as mixed units

### ISSUE THREAD

**Issue by younies** [icu-units/icu#40]
Currently, we only support Mixed units for simple units. For example "foot-and-inch",

However, we need to support complex mixed units, such as "foot-per-hour-and-inch-per-hour"

DESIGN:
  Add MixedUnitImpl.

**Comment by sffc** [comment]
> However, we need to support complex mixed units, such as "foot-per-hour-and-inch-per-hour"

Why do we need it?

We had a discussion about this subject in the spring and decided not to include complex mixed units.

**Comment by younies** [comment]
At least we need a function that returns list of `MeasureUnitImpl` objects that represented the sequence of the units inside the MeasureUnitImpl

for example: 

- `foot-per-second` should return a list of 1 element
- `foot-and-inch` should return a list of 2 elements (`foot` , `inch`) in a `MeasureUnitImpl` format.

**Comment by younies** [comment]
For now, I need to convert MeasureUnitImpl units from `SingleUnitImpl` to `MeasureUnitImpl` when I need to extract all the units (I mean the singleton units) in `MeasureUnitImpl`

**Comment by hugovdm** [comment]
I don't understand this either - let's talk in a sync meeting about the use case? If this is related to https://github.com/icu-units/icu/pull/15 - please just (first) do what can be done without adding new APIs?

**Comment by sffc** [comment]
I think it's fine to do the conversion from `SingleUnitImpl` to `MeasureUnitImpl`.  I saw that in one of your PRs and I thought it was fine.

**Comment by hugovdm** [comment]
I see it too now and I am now less confused, thanks. :)

**Comment by sffc** [comment]
Upstream ticket: https://unicode-org.atlassian.net/browse/CLDR-13701
