### ISSUE TITLE
Upstreaming of Units work

### ISSUE THREAD

**Issue by hugovdm** [icu-units/icu#42]
I have started tiding up the git commit history in my [hugovdm_upstreaming branch](https://github.com/hugovdm/icu/tree/hugovdm_upstreaming), in preparation for upstreaming. I rewrite history to do so, so this is in the hugovdm repository for now. Please don't branch off of this branch, unless you're very happy doing lots of rebasing.

I'm preserving authorship as best possible, with some history-simplifying suggestions on the way.

My process is roughly:

- Manually rebase/squash the units-staging history, to obtain one commit per units-staging Pull Request.
- Squash some consecutive Pull Requests by the same author when they're sufficiently related.
- Drop Pull Requests that become no-op since they've already been upstreamed (following upstream/master merges into units-staging).
- Further changes as necessary...
- Verify whenever reasonable that the `hugovdm_upstreaming` branch has exactly the same content as the `units-staging` branch.

## Reviewing the work so far

If anyone wants to trace my steps taken so far, fetching the hugovdm_upstreaming_{step*,noop*} tags and hugovdm_upstreaming branch from the hugovdm repository allows this review:

$ git log --oneline --decorate --graph hugovdm_upstreaming_step{1,2,3} hugovdm_upstreaming_noop1 hugovdm/hugovdm_upstreaming

- tag: hugovdm_upstreaming_step1 - the end result of a lot of rebasing work, overlapping merge histories were much more work of course.
- tag: hugovdm_upstreaming_noop1 - the subset of PRs that have already been upstreamed: squashed together and rebased on upstream, these 14 commits become a no-op, so it was a bit of busywork? :-) Was satisfying though.
- tag: hugovdm_upstreaming_step2 - the remaining commits from step1 (i.e. step1 commits minus the commits from noop1)
- tag: hugovdm_upstreaming_step3 - some squashing of the earlier history, such that each commit alternates between my work and younies' work (use gitk, or `git log` without the `--oneline`).
- branch: hugovdm_upstreaming - continuation of one-commit-per-PR, covering four merged PRs since last week.

I want a branch in the icu-units repository that maps to the point we last merged upstream into units-staging. Locally I have "master_lastmerge", I can push that to icu-units, or we could keep the "master" branch pointing at the commit representing this base.

## Next Steps

I will merge upstream/master into units-staging again after PR 15 is merged. (I probably won't wait for PR 6, it touches only one file plus the dependencies.txt file.) Then I can rebase and end a PR on which we can comment on the preferred history.

I will probably interleave some new commits that will help shuffle some of the edits around to simplify the history, and then squash them in a next step. These commits could be reviewed, perhaps? I can highlight them as I go.

An example:

- Consider commit A by author1, touching file1, file2, file3,
- Consider commit C by author2, touching file4, file5, and making a small correction to file2,
- I will introduce a commit B that contains the edits to file2 from commit C.
  - We would have commit history "A - B - C_", allowing review of B as desired (C_ being C without the edits now in B).
- Next squashing A and B together to produce "AB - C_", losing info on author2's edits to file2.
  - The result is that "AB" and "C_" can be reordered, since they don't touch the same files.
- Consider commit D by author1. "A - C - D" could not be simplified without losing authorship info.
  - "AB - C_ - D" can be reordered to "C_ - AB - D", and then "AB" and "D" can be merged into one commit.

This may sound excessive. I enjoy it though, and it's fairly straight forward now that I have the worst of the overlapping merge histories sorted out. Upstreaming changes to existing ICU files can similarly be done, prior to any upstream PR for new Units-related files.

**Comment by hugovdm** [comment]
Comparing hugovdm_upstreaming to icu-units/master branches:
https://github.com/icu-units/icu/compare/master...hugovdm:hugovdm_upstreaming?expand=1

- cmemory.h change can be upstreamed.
- Part of the measunit_extra.cpp changes are already upstreamed (not sure why they show up), some more can be upstreamed.
- I've done some ad-hoc doc tweaks in formatted_string_builder.h, number_decimalquantity.h, number_types.h, etc - I might upstream tweaks like these separately, and/or I might remove them from units-staging (undoing them)...

(And if we can get the ICU folk to permit a two-commit PR (to then rebase-and-merge), we can try to squash the eventual PR's commits down to two.)

**Comment by sffc** [comment]
> This may sound excessive. I enjoy it though, and it's fairly straight forward now that I have the worst of the overlapping merge histories sorted out.

:smiley:

**Comment by hugovdm** [comment]
* tag: hugovdm_upstreaming_step4 - seven more PRs added.
* tag: hugovdm_upstreaming_step5 - rebased on upstream/master, conflicts resolved to compilable.
* tag: hugovdm_upstreaming_step6 - interleaved four fixup commits to make each commit in the rebased branch compile successfully.
* tag: hugovdm_upstreaming_step7 - git rebase --autosquash (fixup commits folded in).

**Comment by hugovdm** [comment]
* tag: hugovdm_upstreaming_step8 - same content, rewritten commit messages.
* tag: hugovdm_upstreaming_step9 - four commits: three more PRs, plus a small (cherry-picked) one to make the next rebase easier.
* tag: hugovdm_upstreaming_step10 - both rebased on newer units-staging, and three more commits / PRs.
* HEAD: updated to latest upstream/master. (upstream/master merged into units-staging, hugovdm_upstreaming rebased onto upstream/master, zero diffs relative to the latest units-staging.)

(I'm no longer tagging right after a rebase, just before the next rebase. The commit messages makes it easier enough to recognise where the new PRs resumed.)

**Comment by hugovdm** [comment]
* tag: hugovdm_upstreaming_step11 - rebased onto newer units-staging, then five more PRs / commits on top of that.

I've created https://github.com/unicode-org/icu/pull/1284 which will be the upstreaming PR.

**Comment by sffc** [comment]
You can use this jira issue: https://unicode-org.atlassian.net/browse/ICU-20568

**Comment by hugovdm** [comment]
* tag: hugovdm_upstreaming_step12:
  * added ICU-20568 prefix to commit messages lacking a ticket prefix. (One commit had one, I'm expecting a complaint about it being different.)
  * added two more commits / PRs.
  *rebased on latest upstream/master, ~frozen for review

**Comment by hugovdm** [comment]
* tag: hugovdm_upstreaming_step13:
  * rebased onto newer units-staging / newer upstream/master
  * consistent ticket numbers throughout.
* tag: hugovdm_upstreaming_step14:
  * added some more edits, most for squashing into earlier PRs.
* tag: hugovdm_upstreaming_step15: identical content to step14
  * expanded the commits
  * rewrote new commits' commit messages (most are squash!)

**Comment by hugovdm** [comment]
tag: hugovdm_upstreaming_step16: added three more squash commits (changes also in #75).
tag: hugovdm_upstreaming_step17: reordered commits, mostly not yet squashed (just one already-squashed edit to measfmt.h).
tag: hugovdm_upstreaming_step18: squash!

```
pick 6d635c2c05 ICU-20568 Skeleton for Testing Units
pick 15da9df0c3 ICU-20568 unitsdata.cpp and associated tests (7 PRs)
pick efa1140903 ICU-20568 Check convertible units
pick 7fdc5e38cc ICU-20568 testConversions: test convertibility of unitsTest.txt test cases.
pick 5cb4ca52b7 ICU-20568 Add unit converter.
pick 04fa0f3750 ICU-20568 getPreferencesFor() and getUnitCategory() (4 PRs)
squash 0a627a8862 squash! CI fix for source/i18n/unitsdata.h
squash b938f75002 squash! CI fix for source/test/intltest/unitsdatatest.cpp
pick 621ddcd88a ICU-20568 add usage to number formatter settings header
pick 559c18879f ICU-20568 Change getPreferencesFor parameters from char* to StringPiece.
pick 85b588b794 ICU-20568 Implementation of UnitsRouter and ComplexUnitConverter.
pick df001d95ab ICU-20568 Unit test improvements (the rest of PR already upstreamed).
pick 991f318ead ICU-20568 Implement Usage "Glue Code"
squash a4b674cc2a squash! CI fix for source/i18n/number_usageprefs.cpp
pick 7a6173258a ICU-20568 Use namespace ::icu::units::impl for units-related code.
pick 88fc09fc44 ICU-20568 Export addSingleFactorConstant in header file
pick 99f3f3348b ICU-20568 Fix MeasureUnit identifiers to be spec-compliant.
pick d03023bfd3 ICU-20568 Cleanup: IWYU headers (with some exceptions), SigNum -> Signum
pick 0f97caf2d9 ICU-20568 Test that addSingleFactorConstant knowns all unitConstants.
pick 3cebc277b0 ICU-20568 Add Unit Usage support to Number Skeletons.
pick e8ffa29dec ICU-20568 Add precision to the output of UnitsRouter#route
pick 13c953a03a ICU-20568 Fix some compiler warnings
pick 469ace95bd ICU-20568 Use `Impl` libraries for all internal libraries
pick 37bc8493d9 ICU-20568 Fix compiler warnings
pick e8267a846c ICU-20568 add comment about ratesInfo param in UnitConverter
pick e7cdc5f3de ICU-20568 Explore Usage-related error codes, address icu-units/icu#36.
pick 6b247a2a5e ICU-20568 Implement Precision handling in UsagePrefsHandler::processQuantity
pick a0a3381ec3 ICU-20568 Support Mixed Units in NumberFormatter when using usage()
squash e978553867 squash! CI fix for source/i18n/number_microprops.h
pick 4cbab9bb97 ICU-20568 For MixedUnits, use the correct ListFormatter styles.
pick 986bd170d0 ICU-20568 Read the CLDR testData test files from the new location.
pick abd1efe191 ICU-20568 Sort the units in ComplexUnitConverter
pick 94600d018f ICU-20568 Fix double-precision maths in unit conversions
pick 0430ef219b ICU-20568 Support .unit(MIXED_UNIT) without .usage(...).
pick 16d7ad546d ICU-20568 Reorder numbertest_api.cpp tests for consistent order.
pick b5b91a423b ICU-20568 NumberFormatterApiTest: fold unitPipeline() into unitCompoundMeasure()
```

**Comment by hugovdm** [comment]
- tag: hugovdm_upstreaming_step19: some more commits.
- tag: hugovdm_upstreaming_step20: squashed couple of commits, added several more, got review from sffc on 2020-09-08.
- tag: hugovdm_upstreaming_step21: rebased
- tag: hugovdm_upstreaming_step22: some commit splitting and squashing, and Author rewriting for consistency
- tag: hugovdm_upstreaming_step23: aggressive squash down to 12 commits.

**Comment by hugovdm** [comment]
- tag: [hugovdm_upstreaming_step25](https://github.com/hugovdm/icu/releases/tag/hugovdm_upstreaming_step25): added two fixup commits (thus deviating again from step20).

**Comment by hugovdm** [comment]
- tag: [hugovdm_upstreaming_step26](https://github.com/hugovdm/icu/releases/tag/hugovdm_upstreaming_step26): one more fixup commit, another typo fix
- tag: [hugovdm_upstreaming_step27](https://github.com/hugovdm/icu/releases/tag/hugovdm_upstreaming_step27): the final state when it was "rebase and merge"-ed!
