### ISSUE TITLE
ICU-21306 Update CLDR-to-ICU for Units to CLDR 38

### ISSUE THREAD

**Issue by sffc** [icu-units/icu#48]
**Issue Status**
- [X] add unitPrefixPattern
- [x] unitPattern new case attribute
- [x] unit new gender subelement
- [X] compoundUnit more types
- [X] compoundUnitPattern1 new gender/case attributes (add compoundUnitPattern1)
- [x] compoundUnitPattern new case attribute

Message from @pedberg-icu:

> Currently one step in CLDR to ICU integration is updating the MeasureUnit/Format code in ICU, using the process in
http://site.icu-project.org/design/formatting/measureformat/updating-measure-unit
which uses some tooling in icu4c/main/tests/core/src/com/ibm/icu/dev/test/format/MeasureUnitTest.java
>
> CLDR 38 has some significant changes to the structure of units data, including:
> - unitPattern new case attribute
> - unit new gender subelement
> - compoundUnit more types
> - compoundUnitPattern1 new gender/case attributes
> - compoundUnitPattern new case attribute
>
> Has there already been some thinking about:
> 1. How we want to have that data expressed in ICU structure?
> 2. How to update the tooling in MeasureUnitTest.java to handle the updated units structure and types?
>
> Thanks,
> - Peter E
> (BTW I will be out from July 31 through about August 23)

**Comment by hugovdm** [comment]
On point 2: I hope ldml2icu rules will be sufficient, with code reading the necessary data from resources.

On point 1: this work will commence soon, as we start working on inflections.

On the process in http://site.icu-project.org/design/formatting/measureformat/updating-measure-unit - I wil update this for https://github.com/icu-units/icu/issues/37, having also just gone through the motions of getting MeasureUnitTest.java and the code back in sync.

**Comment by hugovdm** [comment]
Multiple steps:

- I'll tackle binary prefixes first, relatively straight forward, and showing how it's done,
- next we'll tackle the various compound units,
- third, if we don't immediately cover all of it by the compound units work, we need to add the remaining gender and case data.

As mentioned: I'm doing binary prefixes, ensuring documentation is reasonably clear and showing Younies how to do this too. Then we'll determine how we divide up the remaining CLDR data import work.

**Comment by hugovdm** [comment]
Edited @sffc's initial message at the top to add checkboxes for what's done.

**Comment by hugovdm** [comment]
Checked the list of things covered by #1566 against http://cldr.unicode.org/index/downloads/cldr-38 - when 1566 is merged, this ticket is done.
