### ISSUE TITLE
Determine and implement desired behaviour for .unit(builtInCompoundUnit).perUnit(anotherUnit)

### ISSUE THREAD

**Issue by hugovdm** [icu-units/icu#59]
**Jira ticket: https://unicode-org.atlassian.net/browse/ICU-21266**

Document for proposed behaviour for ICU 68 and ICU 69: https://docs.google.com/document/d/1RBqTk-ASKFBM2xom7Bzr6fxKXWXnL4gYFchG3CYK_bQ/edit#

(The "m/s/s" aspect below might need to be broken off into a new ticket.)

Currently one can do this:

    auto nf = NumberFormatter::with()
             .unit(MeasureUnit::getMeterPerSecond())
             .perUnit(MeasureUnit::getSecond());

meter-per-square-second is actually a built-in unit, so in theory this could be supported. However MeasureUnit::resolveUnitPerUnit() attempts to resolve this using the unitPerUnitToSingleUnit array, which doesn't have an entry with "meter-per-second" as an input - there's no "439" in this array.

    offset meter: 390
    offset second: 350
    offset meterPerSecond: 439

- We should check up on the update procedure for unitPerUnitToSingleUnit if we care about it being reliable or more thorough. (Out of scope for this ticket.)
- We in any case need to deal with `.unit(builtin1).perUnit(builtin2)` where the result is *not* a built-in unit. So what do we expect in that case? An error?

Currently it is not an error, but the formatting output is `2.4 m/s/s`. Maybe we can't turn it into an error? In that case we *have* to support `.unit(builtin1).perUnit(builtin2)`, and just need to be more thorough to resolve this to meter-per-square-second?

**Comment by sffc** [comment]
We could use MasureUnit arithmetic to resolve the per unit, and then MeasureUnit should automatically pick the right built-in unit for it.  Then we can throw out `resolveUnitPerUnit()`.

**Comment by hugovdm** [comment]
I filed ICU-21266 so I can refer to it in TODOs in numberformatter.h (https://github.com/unicode-org/icu/pull/1289).

**Comment by hugovdm** [comment]
Document for proposed behaviour for ICU 68 and ICU 69: https://docs.google.com/document/d/1RBqTk-ASKFBM2xom7Bzr6fxKXWXnL4gYFchG3CYK_bQ/edit#

**Comment by hugovdm** [comment]
Should be fixed as soon as 1347 is merged.
