### ISSUE TITLE
Deal with list styles for mixed units

### ISSUE THREAD

**Issue by hugovdm** [icu-units/icu#60]
https://github.com/icu-units/icu/pull/52 is producing `"13,802 st and 7.2 lb"`.

We should support at least two of narrow/short/wide, producing something like `"13,802 st, 7.2 lb"` or `"13,802 stones and 7.2 pounds"`.

**Comment by hugovdm** [comment]
I'm leaving it as a separate ticket and pull request so that we can more easily discuss the style choices without the noise of the rest of the basic mixed unit support PR.

**Comment by sffc** [comment]
From previous discussions, the width of the list should be the same as the `UnitWidth` choice (macros.unitWidth).

**Comment by hugovdm** [comment]
Need to determine the API or skeletons for this - deciding how individually tunable do we want these parts to be.

For `unit-width-*` I find: narrow, short, full-name, iso-code, formal, variant, hidden.

For ListFormatter widths, looking at ULISTFMT_WIDTH_* shows: wide, short, narrow. But from a ListFormatter::createInstance method, I find "standard", "duration", and "duration-short".

**Comment by hugovdm** [comment]
Given that the list formatter is for formatting "mixed units", the unit-width-* style is all we need. I just need to pick the right ListFormatter style to go with each unit-width-* style. I'll try examples in a couple of languages to try to feel what seems right (and try to cross-reference with sources like news websites or wikipedia).

**Comment by hugovdm** [comment]
It's a fairly small change, I think it's ready to go, but it sits on top of mixedunits.

* Relative to mixedunits: https://github.com/icu-units/icu/compare/mixedunits...liststyles?expand=1
* Relative to units-staging (will use this to create the PR after merging mixedunits, and probably first rebasing liststyles): mixedunits: https://github.com/icu-units/icu/compare/units-staging...liststyles?expand=1

**Comment by sffc** [comment]
Narrow maps to narrow; short maps to short; full name maps to wide.  All others should map to short.  I looks like that's what you're doing in #66.
