### ISSUE TITLE
Add MaybeStackArray::copy, use in class IntMeasures

### ISSUE THREAD

**Issue by hugovdm** [icu-units/icu#64]
* Add a function to MaybeStackArray: `MaybeStackArray MaybeStackArray::copy(UErrorCode&) const` (or maybe name it `clone`)
* IntMeasures' copy assignment function becomes `*this = rhs.clone(status);`

**Comment by hugovdm** [comment]
I think it best to pass in a reference to a MaybeStackArray instance to copy from or to. Not sure which of these two is better:

    void copyInto(MaybeStackArray &dest, UErrorCode &status) const;
    void copyFrom(const MaybeStackArray &src, UErrorCode &status);

Call sites:

            rhs.copyInto(*this, status);
            this->copyFrom(rhs, status);

Maybe the latter looks neater? Could could be simply `copyFrom(rhs, status)`.

**Comment by sffc** [comment]
Your solution in https://github.com/icu-units/icu/pull/81 looks good to me.  Thanks for persisting with this to find the right solution!
