### ISSUE TITLE
Add unit identifier normalization and more parsing tests - ICU-21284

### ISSUE THREAD

**Issue by sffc** [icu-units/icu#70]
Resolve the TODO in measfmttest.cpp (also now in Java):

```
        // TODO(ICU-20920): Add more test cases once the proper ranking is available.
```

***Updates:***
*Following release, it's now https://unicode-org.atlassian.net/browse/ICU-21284*
*Normalization: https://unicode-org.github.io/cldr/ldml/tr35-info.html#Unit_Identifier_Normalization*

**Comment by hugovdm** [comment]
Specification: https://www.unicode.org/reports/tr35/tr35-general.html#Unit_Identifiers
Ideally, closing this issue should mean high confidence that we're spec compliant.

**Comment by hugovdm** [comment]
I propose bumping up to "medium" due to the inclusion of normalization work.
