### ISSUE TITLE
In C++,  Remove sequence word from `Gets the CLDR Sequence Unit Identifier for this MeasureUnit `

### ISSUE THREAD

**Issue by younies** [icu-units/icu#77]
In C++,  Remove sequence word from `Gets the CLDR Sequence Unit Identifier for this MeasureUnit`
in MeasureUnit class.

**Comment by younies** [comment]
after running `ack 'Sequence Unit Identifier'` nothing has been found, thus means it is removed already

**Comment by younies** [comment]
https://github.com/unicode-org/icu/pull/1481

**Comment by hugovdm** [comment]
I found this in the file:

     * @param identifier The CLDR Sequence Unit Identifier

**Comment by hugovdm** [comment]
It was the only "meas"-related use of "sequence" that I found, which wasn't talking about a "sequence of units" or "sequence of measures" - so we'll still fix that reference with this ticket.
