### ISSUE TITLE
Make C++ code looks like Java in UnitConverter, UnitsData, Extracting Factors ... etc.

### ISSUE THREAD

**Issue by younies** [icu-units/icu#82]
Many internal libraries in Java are slightly different and organised than C++ because it is developed after the whole picture was revealed.

Therefore, we need to make C++ code looks like java.

Especially in UnitConverter, UnitsData, Extracting Factors, ... etc.

**Comment by hugovdm** [comment]
Can we rename this ticket to "Revisit and clean up C++ and Java code"? (The Java code is not always better than the C++ code.)

**Comment by hugovdm** [comment]
Looks like reciprocal conversions are broken in Java. My apologies for not having added good tests for this earlier!

I'm not intending to do all of this one, just enough to get the unit tests fixed.

**Comment by hugovdm** [comment]
Is this issue really fixed? The PR that closed it, https://github.com/unicode-org/icu/pull/1876, does not cover what this bug covers.

(That PR also has an unresolved comment from Frank, for some additional improvements possible in the unit test.)
