### ISSUE TITLE
canonicalizes is not an english word

### ISSUE THREAD

**Issue by younies** [icu-units/icu#85]
In the MeasureUnit::getIdentifier doc.

```
         * Construct a MeasureUnit from a CLDR Unit Identifier, defined in UTS 35.
         * Validates and canonicalizes the identifier.
```

however, canonicalizes is not an english word

**Comment by hugovdm** [comment]
Canonicalize is a verb (e.g. https://en.wiktionary.org/wiki/canonicalize / https://en.wikipedia.org/wiki/Canonicalization). Verbs in third-person singular get an "s" on the end, thus "canonicalizes".
