### ISSUE TITLE
Make C++ singleUnitParser looks like Java

### ISSUE THREAD

**Issue by younies** [icu-units/icu#87]
The string `meter-square-meter` should get normalized to `cubic-meter` as soon as it is parsed. therefore, the unit will be SingelUnit.

In Java code, we have fixed this issue, we need to fix it in C++ too and make the code looks like Java.

Also, add test cases to ensure the correct behaviour

**Comment by hugovdm** [comment]
I'm assigning this the ICU 68 milestone? Mostly for the "meter-square-meter" issue.
