### ISSUE TITLE
Port C++ test cases to Java for UnitConveter, UnitsRouter, ComplexUnitsConverter

### ISSUE THREAD

**Issue by younies** [icu-units/icu#92]
There are couple of test cases such as test the freshness of the constants  that it is better to be added to Java code too.

**Comment by hugovdm** [comment]
2020-Q4-W1 or 2020-Q4-W2, perhaps?

**Comment by hugovdm** [comment]
I need UnitsTest::testConverter() as I'm adding binary prefixes. I'll probably go ahead and add it, but leave the rest of this ticket?

**Comment by hugovdm** [comment]
I'm reopening: I can't find testUnitConstantFreshness in ICU4J. Has it been added?

**Comment by hugovdm** [comment]
Here's an example of a diff with which "ant check" still passes all core tests:

```
--- a/icu4j/main/classes/core/src/com/ibm/icu/impl/units/UnitConverter.java
+++ b/icu4j/main/classes/core/src/com/ibm/icu/impl/units/UnitConverter.java
@@ -315,8 +315,8 @@ private void addEntity(String entity, int power) {
                 this.exponentFtToM += power;
             } else if ("ft2_to_m2".equals(entity)) {
                 this.exponentFtToM += 2 * power;
-            } else if ("ft3_to_m3".equals(entity)) {
-                this.exponentFtToM += 3 * power;
+            // } else if ("ft3_to_m3".equals(entity)) {
+            //     this.exponentFtToM += 3 * power;
             } else if ("in3_to_m3".equals(entity)) {
                 this.exponentFtToM += 3 * power;
                 this.factorDen = this.factorDen.multiply(BigDecimal.valueOf(Math.pow(12, 3)));
@@ -326,16 +326,16 @@ private void addEntity(String entity, int power) {
                 this.factorDen = this.factorDen.multiply(BigDecimal.valueOf(12 * 12 * 12));
             } else if ("gal_imp_to_m3".equals(entity)) {
                 this.exponentGalImpToM3 += power;
-            } else if ("G".equals(entity)) {
-                this.exponentG += power;
+            // } else if ("G".equals(entity)) {
+            //     this.exponentG += power;
             } else if ("gravity".equals(entity)) {
                 this.exponentGravity += power;
             } else if ("lb_to_kg".equals(entity)) {
                 this.exponentLbToKg += power;
-            } else if ("glucose_molar_mass".equals(entity)) {
-                this.exponentGlucoseMolarMass += power;
-            } else if ("item_per_mole".equals(entity)) {
-                this.exponentItemPerMole += power;
+            // } else if ("glucose_molar_mass".equals(entity)) {
+            //     this.exponentGlucoseMolarMass += power;
+            // } else if ("item_per_mole".equals(entity)) {
+            //     this.exponentItemPerMole += power;
             } else if ("PI".equals(entity)) {
                 this.exponentPi += power;
             } else {

```

Which means test coverage is very much insufficient to cover all cases. It seems the constants are only parsed when the conversion rates are actually used. For such manually updated code (where a CLDR release could mean someone not familiar with the code needs to go add a bunch of members to the Factor class), I'd ideally want tests to cover each possible constant's impact on Factor.copy(), Factor.getConversionRate(), Factor.power(), Factor.divide(), Factor.multiply(), and Factor.addEntity().

Considering this, it might rather be easier to convert the Java code to use an array with an enum for indexes, in similar fashion to the C++ code. This would mean fewer things need to change for each new constant, thus fewer chances for errors.

Should I rather file a new Issue to track this?

**Comment by sffc** [comment]
I think the idea is that we don't really need testUnitConstantFreshness in *both* C and J because if it fails in one, it should alert the author that they need to update both places, and the reviewers should enforce that.  Of course, that's prone to human error, but less than if we didn't have the test at all.  So I think it's useful but not high-priority to port the case to J.

**Comment by hugovdm** [comment]
I can file a separate ticket to track that then, so we could consider closing this one.

Working on unit categories now though, dealing with the consumption-inverse change, I find more unit tests missing:

UnitsDataTest (units_data_test.cpp) has three tests: testGetUnitCategory, testGetAllConversionRates, testGetPreferencesFor.

This isn't covered by the title of this Issue, so I guess that could also go into a new ticket?

**Comment by sffc** [comment]
Yeah, make a new ticket for the data tests.

**Comment by hugovdm** [comment]
Done: I created a new issue with a fairly verbose description, and labelled it "future": https://github.com/icu-units/icu/issues/128

**Comment by hugovdm** [comment]
For porting of UnitsDataTest: https://github.com/icu-units/icu/issues/129 - I'm currently considering these deprioritised. I've not labelled that issue yet though.
