### ISSUE TITLE
ICU-21288 Revisit precision handling for mixed units

### ISSUE THREAD

**Issue by hugovdm** [icu-units/icu#94]
[ICU-21288](https://unicode-org.atlassian.net/browse/ICU-21288)
Currently we're applying precision handling to the smallest unit in the mixed unit case. This doesn't give balanced results across locales - two examples with vastly different precision:

- 9° 31' 9.3"
- 9.5°

These would currenlty be produced by "one decimal figure" as well as "two significant digits". Thus: reconsider how these precisions are calculated, and which of the cases we could handle better.

**Comment by hugovdm** [comment]
Some of this might be pretty tricky, to get "accurate" decimal rounding. The theoretically most accurate results might require translating the precision itself to the output units before doing the rounding.

**Comment by macchiati** [comment]
We'll have to think through what makes a reasonable result, but we need to do better than 2 digits of accuracy causes <9° 31' 9.3">

**Comment by hugovdm** [comment]
I have filed an ICU ticket: https://unicode-org.atlassian.net/browse/ICU-21288

**Comment by younies** [comment]
Move it to jira

**Comment by younies** [comment]
[ICU-21288](https://unicode-org.atlassian.net/browse/ICU-21288)
