### ISSUE TITLE
Fix the rounder in Java

### ISSUE THREAD

**Issue by younies** [icu-units/icu#95]

**Comment by sffc** [comment]
Consider making a BogusPrecision class:

![image](https://user-images.githubusercontent.com/1145762/93250799-f3f00e80-f758-11ea-88ae-619b2870b554.png)

**Comment by hugovdm** [comment]
Fixed in https://github.com/unicode-org/icu/pull/1326 (commit 143395f93e - will get squashed away).

**Comment by hugovdm** [comment]
Marking as closed, even though 1326 isn't submitted yet. (This ticket was filed while 1326 was still skipping the "bogus precision" code.)
